# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches:
      - "release"
      - "develop"
      - "hotfix"
      - "feature/**"
  pull_request:
    branches:
      - "main"
      - "release"
      - "develop"
      - "hotfix"
      - "feature/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore AuthGatun.sln
    - name: Build solution
      run: dotnet build AuthGatun.sln --configuration Release --no-restore
    - name: Run tests
      run: dotnet test AuthGatun.Tests/AuthGatun.Tests.csproj --no-build --configuration Release
