name: Release Native AOT

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore AuthGatun.sln

      - name: Publish (Linux AOT)
        run: |
          dotnet publish AuthGatun/AuthGatun.csproj \
            -c Release \
            -r linux-x64 \
            -p:PublishAot=true \
            --self-contained true \
            -o out/linux

      - name: Zip Linux build
        run: |
          cd out/linux
          zip -r ../../AuthGatun-linux-x64.zip .

      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: AuthGatun-linux-x64.zip

  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore AuthGatun.sln

      - name: Publish (Windows AOT)
        run: |
          dotnet publish AuthGatun\AuthGatun.csproj `
            -c Release `
            -r win-x64 `
            -p:PublishAot=true `
            --self-contained true `
            -o out/windows

      - name: Zip Windows build
        run: |
          Compress-Archive -Path out/windows/* -DestinationPath AuthGatun-win-x64.zip

      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: AuthGatun-win-x64.zip

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: linux-build
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: "Builds para Linux y Windows (Native AOT)"
          files: |
            AuthGatun-linux-x64.zip
            AuthGatun-win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
